name: receive_sharing_intent
description: A flutter plugin that enables flutter apps to receive sharing photos, text or url from other apps.
version: 1.9.0
homepage: https://github.com/KasemJaffer/receive_sharing_intent

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  
  plugin:
    platforms:
      android:
        package: com.kasem.receive_sharing_intent
        pluginClass: ReceiveSharingIntentPlugin
      ios:
        pluginClass: ReceiveSharingIntentPlugin
